### ISSUE TITLE
Says chromedriver isn't in the path..

### ISSUE THREAD

**Issue by TheOncomingStorm** [milo2012/osintstalker#1]
I downloaded and installed chromedriver to /usr/bin as well as the current path. I also ran chromedriver in the background just in case it was having trouble starting it or the like but I still get this

Any idea? 

Traceback (most recent call last):
  File "fbstalker.py", line 61, in <module>
    driver = webdriver.Chrome(chrome_options=chromeOptions)
  File "/usr/lib/python2.7/site-packages/selenium-2.37.0-py2.7.egg/selenium/webdriver/chrome/webdriver.py", line 59, in **init**
    self.service.start()
  File "/usr/lib/python2.7/site-packages/selenium-2.37.0-py2.7.egg/selenium/webdriver/chrome/service.py", line 68, in start
    and read up at http://code.google.com/p/selenium/wiki/ChromeDriver")
selenium.common.exceptions.WebDriverException: Message: 'ChromeDriver executable needs to be available in the path.                 Please download from http://code.google.com/p/chromedriver/downloads/list                and read up at http://code.google.com/p/selenium/wiki/ChromeDriver'

**Comment by Jaywalker** [comment]
Download Chromedriver at the link on the googlecode site. Ensure it is in a directory in your $PATH

**Comment by TheOncomingStorm** [comment]
I found the problem. It was the file permissions on /usr/bin/chromedriver.  chmod 755 /usr/bin/chromedriver worked.
