### ISSUE TITLE
Crash on UnicodeEncodeError

### ISSUE THREAD

**Issue by martinhedstrom** [milo2012/osintstalker#12]
Is there a way to get around FBStalker crashing on users with unicode characters? The script is running fine for me on Kali Linux but crashes on UnicodeEncodeError.

Also, it took a while for me to figure out that I need to use a 64-bit Chromedriver to get this beast running. Maby you could include the link to that one in the installation instructions. 

Thanks
Martin

```
Traceback (most recent call last):
  File "fbstalker1.py", line 2030, in <module>
    options(sys.argv)
  File "fbstalker1.py", line 1974, in options
    mainProcess(user)
  File "fbstalker1.py", line 1913, in mainProcess
    dataList = parseTimeline(html,username)
  File "fbstalker1.py", line 522, in parseTimeline
    print "[*] Location of Post: "+str(tlDateTimeLoc[1].text)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf6' in position 1: ordinal not in range(128)
```

**Comment by martinhedstrom** [comment]
Following Amnesthesias instructions replacing str() with unicode() in def parseTimeline(html,username) did solve the problem. Great!

**Comment by canarybearer** [comment]
Would you mind sharing the code you changed please? I seem to still be getting the error.

**Comment by martinhedstrom** [comment]
Ofcourse!
I replaced str() with unicode() in function parseTimeline(html,username). 
I edited rows 522,524,533 and 535 (so check around there, depending on how your script is set up)

```
            if len(tlDateTimeLoc)>2:
                try:
                    #Device / Location
                    if len(tlDateTimeLoc[1].text)>0:
                        print "[*] Location of Post: "+unicode(tlDateTimeLoc[1].text)
                    if len(tlDateTimeLoc[2].text)>0:
                        print "[*] Device: "+unicode(tlDateTimeLoc[2].text)
                except IndexError:
                    continue    

            else:
                try:
                    #Device / Location
                    if len(tlDateTimeLoc[1].text)>0:
                        if "mobile" in tlDateTimeLoc[1].text:
                            print "[*] Device: "+unicode(tlDateTimeLoc[1].text)
                        else:
                            print "[*] Location of Post: "+unicode(tlDateTimeLoc[1].text)
```

**Comment by th3l0b3** [comment]
I am getting this error, even after these changes.  Do you have any issues with your script at all?  If not, would you be able to share your code with the username/passwd edited out?
