### ISSUE TITLE
Error: Traceback (most recent call last) ...

### ISSUE THREAD

**Issue by mikysal78** [milo2012/osintstalker#21]
After auto-opening the page Facebook of login,  I'have this error:
File "fbstalker1.py", line 2030, in <module>
    options(sys.argv)
File "fbstalker1.py", line 1748, in mainProcess
     loginFacebook(driver)
File "fbstalker1.py", line 326, in loginFacebook
    assert "Welcome to Facebook" in driver.title
AssertionError

Because?

**Comment by emmanuelb23** [comment]
That error is caused because the facebook page you're trying to load is in another language that is not english, just comment the line.
