### ISSUE TITLE
httplib2 no module

### ISSUE THREAD

**Issue by tomahock** [milo2012/osintstalker#4]
Hi when i try to run it gives me this error:

```
➜  osintstalker git:(master) python fbstalker.py -u XXXX -report report.txt
Traceback (most recent call last):
  File "fbstalker.py", line 3, in <module>
    import httplib2,json
ImportError: No module named httplib2
```

But i got httplib2 installed:

```
➜  ~  pip install httplib2
Requirement already satisfied (use --upgrade to upgrade): httplib2 in /usr/local/lib/python2.7/site-packages
Cleaning up...
```

Any guess?

**Comment by milo2012** [comment]
Try python2.6 . I have not tested it on Python2.7 yet.  I will do so in the next couple of days.

wget http://www.python.org/ftp/python/2.6/Python-2.6.tgz
tar xvfz python/2.6/Python-2.6.tgz
./configure && make && make install

wget https://pypi.python.org/packages/source/s/setuptools/setuptools-1.1.6.tar.gz
tar xvfz setuptools-1.1.6.tar.gz
cd setuptools-1.1.6
python2.6 setup.py install

easy_install-2.6 pip
pip-2.6 install httplib2

**Comment by milo2012** [comment]
I have tested the code on Python2.7. Let me know if you have any issues

sudo apt-get install python-setuptools

wget https://pypi.python.org/packages/source/p/pip-2.7/pip-2.7-1.4.1.tar.gz
tar xvfz pip-2.7-1.4.1.tar.gz
cd pip-2.7-1.4.1
sudo python2.7 setup.py install

git clone https://github.com/hadim/pygraphml.git
cd pygraphml
python2.7 setup.py install

pip-2.7 install google
pip-2.7 install python-instagram
pip-2.7 install pygoogle
pip-2.7 install geopy
pip-2.7 install lxml
pip-2.7 install oauth2
pip-2.7 install python-linkedin
pip-2.7 install pygeocoder
pip-2.7 install selenium
pip-2.7 install termcolor
pip-2.7 install pysqlite
pip-2.7 install TwitterSearch
pip-2.7 install foursquare

wget https://gdata-python-client.googlecode.com/files/gdata-2.0.18.tar.gz
tar xvfz gdata-2.0.18.tar.gz
cd gdata-2.0.18
python2.7 setup.py install

python2.7 geoStalker.py

**Comment by tomahock** [comment]
It works :)
