### ISSUE TITLE
geostalker.py - IndexError: list index out of range

### ISSUE THREAD

**Issue by MikeTuffin** [milo2012/osintstalker#6]
Please enter an address or GPS coordinates (e.g. 4.237588,101.131332): 4.237588,101.131332
[_] Converting address to GPS coordinates: 4.237588 101.131332
[_] Downloading Wigle database from Internet
[_] Saving wigle database to: 4.237588_101.131332.dat
[_] Converting Wigle database to KML format.
[_] Convert Wigle Database to KML format
[_] Convert wigle database to: 4.237588_101.131332.kml
[_] Wigle database already exists: 4.237588_101.131332.dat
[_] Checking Google Docs if File Exists
[_] Logging in... Login success!
[_] File does not exists!
[_] Uploading: 4.237588_101.131332.kml to Google Docs!
[_] Logging in... Login success!
Fetching collection ID... success!
Starting uploading of file... Upload success!
[_] Change: 4.237588_101.131332.kml Access to Public
[_] Logging in... Login success!
owner user xxxx@gmail.com
Permissions change success!
[_] Extracting MAC addresses from Wigle database: 4.237588_101.131332.dat
[_] Retrieving match for vendor name: Function ATI (Huizhou) Telecommunications Co., Ltd.
[_] Retrieving match for vendor name: ADVANCED MICRO DEVICES
[_] Retrieving match for vendor name: INFORMATION TECHNOLOGY LIMITED
[_]       va corresponds to ADVANCED MICRO DEVICES
[_]       fo corresponds to INFORMATION TECHNOLOGY LIMITED
[*]   functi corresponds to Function ATI (Huizhou) Telecommunications Co., Ltd.
Traceback (most recent call last):
  File "geostalker.py", line 1328, in <module>
    geoLocationSearch(lat,lng)
  File "geostalker.py", line 1236, in geoLocationSearch
    parseWigleDat(filename)
  File "geostalker.py", line 576, in parseWigleDat
    locLat = i.split('~')[11]
IndexError: list index out of range

**Comment by milo2012** [comment]
Could you copy and paste the first two lines from '4.237588_101.131332.dat' in the current directory here ? Thank you

**Comment by MikeTuffin** [comment]
Sent you the file via e-mail as it's HTML.

**Comment by MikeTuffin** [comment]
Change implemented in geostalker.py to include username/password instead of cookie solves this issue, thanks.

**Comment by brianandersone** [comment]
MikeTuffin can you  explain how plz , thnks
